dataset_attributes:
  vtextgqa:
      data_root_dir: /data/zsheng/Data_T5_ViteVQA/data
      image_depth_first: false
      fast_read: false
      features_max_len: 100
      processors:
        context_processor: 
          type: fasttext
          params:
            max_length: 960 # 960 # truncate the max num of OCRs
            model_file: .vector_cache/wiki.en.bin
        ocr_token_processor:
          type: simple_word
          max_length: 960 # 960  
          params: {}
        bbox_processor:
          type: bbox
          params:
            max_length: 960 # 960 
      return_info: true
      use_ocr: true
      use_ocr_info: true